DELIMITER $$

CREATE TRIGGER triger_update_stock AFTER INSERT ON income_detail
FOR EACH ROW BEGIN
UPDATE  product SET stock = stock + NEW.quantity
WHERE id = NEW.product_id;
END$$
DELIMITER;


DELIMITER $$
CREATE TRIGGER triger_sale_stock AFTER INSERT ON sale_detail
FOR EACH ROW BEGIN
UPDATE  product SET stock = stock - NEW.quantity
WHERE id = NEW.product_id;
END$$
DELIMITER;

DELIMITER $$
CREATE TRIGGER delete_income_detail
AFTER INSERT ON income_detail
FOR EACH ROW
BEGIN
 DELETE FROM income_detail WHERE quantity < 1 AND id <> NEW.id;
END$$
DELIMITER;

CREATE TABLE cash_openings ( id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, users_id BIGINT UNSIGNED NOT NULL, start_amount DECIMAL(10,2) NOT NULL, opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, cashbox_name VARCHAR(100) NOT NULL, location VARCHAR(100) DEFAULT NULL, observations TEXT DEFAULT NULL, status ENUM('open', 'closed') DEFAULT 'open', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_cash_openings_users FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ); 